Fix crawler example so it compiles again
Recent changes have caused this example to stop building with an error
like:

```
index.ts:111:33 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.

111             await sites.publish(link);
```

Simply set a type for our set of links.